spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_soft1921?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 1999929
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # 指定接口对应的xml文件所在目录
  mapper-locations: classpath:mapper/*.xml
  #  实体类所在包
  type-aliases-package: xyz.zfdu.boot.mybatis.domain
  configuration:
    map-underscore-to-camel-case: true  # mybatis开启驼峰式命名
